services:
  price-relay:
    build: .
    image: ghcr.io/oasisprotocol/demo-rofl-tgbot:latest
    platform: linux/amd64
    environment:
      - CONTRACT_ADDRESS=0xcF780e57D5ce8E07abCF60AA0aeC9227850db685
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
